import { Room } from "@/types/room";

export const MOCK_ROOMS: Room[] = [
  {
    id: "room-101",
    roomNumber: "101",
    floor: 1,
    type: "Single",
    status: "Occupied",
    lastCleaned: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Rahim",
    currentGuest: {
      name: "John Smith",
      checkInDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      checkOutDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-102",
    roomNumber: "102",
    floor: 1,
    type: "Double",
    status: "Clean",
    lastCleaned: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Maria",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-103",
    roomNumber: "103",
    floor: 1,
    type: "Suite",
    status: "Needs Cleaning",
    lastCleaned: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Ahmed",
    currentGuest: {
      name: "Sarah Johnson",
      checkInDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      checkOutDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-104",
    roomNumber: "104",
    floor: 1,
    type: "Deluxe",
    status: "Under Maintenance",
    lastCleaned: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Fatima",
    maintenanceStatus: {
      issue: "Air conditioning malfunction",
      assignedTo: "Hassan",
      eta: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
      status: "In Progress",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-105",
    roomNumber: "105",
    floor: 1,
    type: "Single",
    status: "Occupied",
    lastCleaned: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Maria",
    currentGuest: {
      name: "Emma Wilson",
      checkInDate: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      checkOutDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-106",
    roomNumber: "106",
    floor: 1,
    type: "Double",
    status: "Clean",
    lastCleaned: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    lastCleanedBy: "Rahim",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-107",
    roomNumber: "107",
    floor: 1,
    type: "Suite",
    status: "Occupied",
    lastCleaned: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Ahmed",
    currentGuest: {
      name: "Michael Brown",
      checkInDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      checkOutDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-108",
    roomNumber: "108",
    floor: 1,
    type: "Deluxe",
    status: "Needs Cleaning",
    lastCleaned: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Fatima",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-109",
    roomNumber: "109",
    floor: 1,
    type: "Single",
    status: "Clean",
    lastCleaned: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Maria",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-110",
    roomNumber: "110",
    floor: 1,
    type: "Double",
    status: "Occupied",
    lastCleaned: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Rahim",
    currentGuest: {
      name: "Linda Davis",
      checkInDate: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      checkOutDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-201",
    roomNumber: "201",
    floor: 2,
    type: "Suite",
    status: "Occupied",
    lastCleaned: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Ahmed",
    currentGuest: {
      name: "Robert Taylor",
      checkInDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      checkOutDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-202",
    roomNumber: "202",
    floor: 2,
    type: "Deluxe",
    status: "Clean",
    lastCleaned: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Fatima",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-203",
    roomNumber: "203",
    floor: 2,
    type: "Single",
    status: "Under Maintenance",
    lastCleaned: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Maria",
    maintenanceStatus: {
      issue: "Water leak in bathroom",
      assignedTo: "Hassan",
      eta: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
      status: "Pending",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-204",
    roomNumber: "204",
    floor: 2,
    type: "Double",
    status: "Needs Cleaning",
    lastCleaned: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Rahim",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-205",
    roomNumber: "205",
    floor: 2,
    type: "Suite",
    status: "Occupied",
    lastCleaned: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Ahmed",
    currentGuest: {
      name: "Patricia Martinez",
      checkInDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      checkOutDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-206",
    roomNumber: "206",
    floor: 2,
    type: "Deluxe",
    status: "Clean",
    lastCleaned: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    lastCleanedBy: "Fatima",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-207",
    roomNumber: "207",
    floor: 2,
    type: "Single",
    status: "Occupied",
    lastCleaned: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Maria",
    currentGuest: {
      name: "James Anderson",
      checkInDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      checkOutDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-208",
    roomNumber: "208",
    floor: 2,
    type: "Double",
    status: "Needs Cleaning",
    lastCleaned: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Rahim",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-209",
    roomNumber: "209",
    floor: 2,
    type: "Suite",
    status: "Clean",
    lastCleaned: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Ahmed",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-210",
    roomNumber: "210",
    floor: 2,
    type: "Deluxe",
    status: "Occupied",
    lastCleaned: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    lastCleanedBy: "Fatima",
    currentGuest: {
      name: "Jennifer Thomas",
      checkInDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      checkOutDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
