import { Task, HousekeepingStaff, ActivityLog, RoomStatus } from "@/types/task";

export const mockStaff: HousekeepingStaff[] = [
  {
    id: "staff-1",
    name: "Rahim Hassan",
    email: "rahim@orionhotel.com",
    phone: "+1-555-0201",
    status: "Active",
    tasksAssigned: 5,
    tasksCompleted: 28,
    averageTimePerTask: 35,
  },
  {
    id: "staff-2",
    name: "Maria Garcia",
    email: "maria@orionhotel.com",
    phone: "+1-555-0202",
    status: "Active",
    tasksAssigned: 4,
    tasksCompleted: 32,
    averageTimePerTask: 32,
  },
  {
    id: "staff-3",
    name: "Ahmed Khalil",
    email: "ahmed@orionhotel.com",
    phone: "+1-555-0203",
    status: "On Break",
    tasksAssigned: 2,
    tasksCompleted: 25,
    averageTimePerTask: 38,
  },
  {
    id: "staff-4",
    name: "Linda Chen",
    email: "linda@orionhotel.com",
    phone: "+1-555-0204",
    status: "Active",
    tasksAssigned: 6,
    tasksCompleted: 35,
    averageTimePerTask: 30,
  },
  {
    id: "staff-5",
    name: "Carlos Rodriguez",
    email: "carlos@orionhotel.com",
    phone: "+1-555-0205",
    status: "Off Duty",
    tasksAssigned: 0,
    tasksCompleted: 40,
    averageTimePerTask: 28,
  },
];

export const mockTasks: Task[] = [
  {
    id: "task-1",
    roomNumber: "101",
    taskType: "Cleaning",
    assignedStaffId: "staff-1",
    priority: "High",
    description: "Deep clean room and change linens",
    dueDate: "2024-01-15",
    dueTime: "10:00",
    status: "In Progress",
    createdAt: "2024-01-15T08:30:00Z",
    assignedAt: "2024-01-15T08:45:00Z",
  },
  {
    id: "task-2",
    roomNumber: "102",
    taskType: "Cleaning",
    assignedStaffId: "staff-2",
    priority: "Medium",
    description: "Standard room cleaning",
    dueDate: "2024-01-15",
    dueTime: "11:00",
    status: "Pending",
    createdAt: "2024-01-15T08:00:00Z",
  },
  {
    id: "task-3",
    roomNumber: "103",
    taskType: "Maintenance",
    assignedStaffId: "staff-4",
    priority: "High",
    description: "Fix bathroom leak",
    dueDate: "2024-01-15",
    dueTime: "14:00",
    status: "Pending",
    createdAt: "2024-01-15T07:45:00Z",
  },
  {
    id: "task-4",
    roomNumber: "104",
    taskType: "Inspection",
    assignedStaffId: "staff-1",
    priority: "Low",
    description: "Weekly room inspection",
    dueDate: "2024-01-15",
    dueTime: "15:00",
    status: "Completed",
    createdAt: "2024-01-15T06:00:00Z",
    completedAt: "2024-01-15T16:15:00Z",
  },
  {
    id: "task-5",
    roomNumber: "105",
    taskType: "Cleaning",
    assignedStaffId: "staff-2",
    priority: "Medium",
    description: "Room refresh and restocking",
    dueDate: "2024-01-15",
    dueTime: "12:00",
    status: "Pending",
    createdAt: "2024-01-15T08:15:00Z",
  },
  {
    id: "task-6",
    roomNumber: "106",
    taskType: "Cleaning",
    assignedStaffId: "staff-4",
    priority: "High",
    description: "VIP room deep clean",
    dueDate: "2024-01-15",
    dueTime: "09:30",
    status: "Completed",
    createdAt: "2024-01-14T16:00:00Z",
    completedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "task-7",
    roomNumber: "107",
    taskType: "Maintenance",
    assignedStaffId: "staff-3",
    priority: "Medium",
    description: "HVAC filter replacement",
    dueDate: "2024-01-15",
    dueTime: "16:00",
    status: "In Progress",
    createdAt: "2024-01-15T08:00:00Z",
    assignedAt: "2024-01-15T08:30:00Z",
  },
  {
    id: "task-8",
    roomNumber: "108",
    taskType: "Cleaning",
    assignedStaffId: "staff-1",
    priority: "Low",
    description: "Turnover cleaning",
    dueDate: "2024-01-15",
    dueTime: "13:00",
    status: "Pending",
    createdAt: "2024-01-15T08:45:00Z",
  },
];

export const mockActivityLogs: ActivityLog[] = [
  {
    id: "log-1",
    taskId: "task-1",
    action: "created",
    staffId: "staff-0",
    staffName: "Admin",
    roomNumber: "101",
    timestamp: "2024-01-15T08:30:00Z",
    details: "Task created for deep cleaning",
  },
  {
    id: "log-2",
    taskId: "task-1",
    action: "assigned",
    staffId: "staff-0",
    staffName: "Admin",
    roomNumber: "101",
    timestamp: "2024-01-15T08:45:00Z",
    details: "Assigned to Rahim Hassan",
  },
  {
    id: "log-3",
    taskId: "task-4",
    action: "completed",
    staffId: "staff-1",
    staffName: "Rahim Hassan",
    roomNumber: "104",
    timestamp: "2024-01-15T16:15:00Z",
    details: "Room marked as clean",
  },
  {
    id: "log-4",
    taskId: "task-6",
    action: "completed",
    staffId: "staff-4",
    staffName: "Linda Chen",
    roomNumber: "106",
    timestamp: "2024-01-15T10:00:00Z",
    details: "VIP room deep clean completed",
  },
  {
    id: "log-5",
    taskId: "task-2",
    action: "assigned",
    staffId: "staff-0",
    staffName: "Admin",
    roomNumber: "102",
    timestamp: "2024-01-15T08:00:00Z",
    details: "Assigned to Maria Garcia",
  },
];

export const mockRoomStatuses: RoomStatus[] = Array.from({ length: 20 }, (_, i) => ({
  roomNumber: String(101 + i),
  status:
    i % 3 === 0 ? "Clean" : i % 3 === 1 ? "In Progress" : "Dirty",
  lastCleaned:
    i % 2 === 0
      ? new Date(2024, 0, 14).toISOString()
      : new Date(2024, 0, 13).toISOString(),
}));
