import { Reservation } from "@/types/reservation";

export const mockReservations: Reservation[] = [
  {
    id: "1",
    bookingId: "BK-001",
    guestName: "John Smith",
    email: "john@example.com",
    phone: "+1-555-0101",
    roomType: "Double",
    checkInDate: "2024-01-15",
    checkOutDate: "2024-01-18",
    numberOfGuests: 2,
    notes: "Late arrival after 6 PM",
    status: "Confirmed",
    paymentStatus: "Paid",
    createdAt: "2024-01-10",
  },
  {
    id: "2",
    bookingId: "BK-002",
    guestName: "Sarah Johnson",
    email: "sarah@example.com",
    phone: "+1-555-0102",
    roomType: "Suite",
    checkInDate: "2024-01-20",
    checkOutDate: "2024-01-25",
    numberOfGuests: 3,
    notes: "Request for high floor",
    status: "Confirmed",
    paymentStatus: "Paid",
    createdAt: "2024-01-12",
  },
  {
    id: "3",
    bookingId: "BK-003",
    guestName: "Michael Chen",
    email: "michael@example.com",
    phone: "+1-555-0103",
    roomType: "Single",
    checkInDate: "2024-01-22",
    checkOutDate: "2024-01-24",
    numberOfGuests: 1,
    notes: "Business travel",
    status: "Pending",
    paymentStatus: "Pending",
    createdAt: "2024-01-13",
  },
  {
    id: "4",
    bookingId: "BK-004",
    guestName: "Emma Wilson",
    email: "emma@example.com",
    phone: "+1-555-0104",
    roomType: "Deluxe",
    checkInDate: "2024-01-10",
    checkOutDate: "2024-01-12",
    numberOfGuests: 4,
    notes: "Honeymoon - special treatment requested",
    status: "Cancelled",
    paymentStatus: "Overdue",
    createdAt: "2024-01-08",
  },
  {
    id: "5",
    bookingId: "BK-005",
    guestName: "David Brown",
    email: "david@example.com",
    phone: "+1-555-0105",
    roomType: "Double",
    checkInDate: "2024-01-28",
    checkOutDate: "2024-02-02",
    numberOfGuests: 2,
    notes: "Extended stay",
    status: "Confirmed",
    paymentStatus: "Paid",
    createdAt: "2024-01-14",
  },
  {
    id: "6",
    bookingId: "BK-006",
    guestName: "Lisa Anderson",
    email: "lisa@example.com",
    phone: "+1-555-0106",
    roomType: "Single",
    checkInDate: "2024-01-18",
    checkOutDate: "2024-01-20",
    numberOfGuests: 1,
    notes: "Conference attendee",
    status: "Confirmed",
    paymentStatus: "Paid",
    createdAt: "2024-01-11",
  },
  {
    id: "7",
    bookingId: "BK-007",
    guestName: "James Martinez",
    email: "james@example.com",
    phone: "+1-555-0107",
    roomType: "Suite",
    checkInDate: "2024-02-05",
    checkOutDate: "2024-02-08",
    numberOfGuests: 3,
    notes: "Family vacation",
    status: "Pending",
    paymentStatus: "Pending",
    createdAt: "2024-01-13",
  },
  {
    id: "8",
    bookingId: "BK-008",
    guestName: "Rachel Green",
    email: "rachel@example.com",
    phone: "+1-555-0108",
    roomType: "Double",
    checkInDate: "2024-01-25",
    checkOutDate: "2024-01-27",
    numberOfGuests: 2,
    notes: "Anniversary celebration",
    status: "Confirmed",
    paymentStatus: "Paid",
    createdAt: "2024-01-12",
  },
];
