import { Invoice } from "@/types/invoice";

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv-001",
    invoiceNumber: "INV-2024-001",
    clientName: "John Smith",
    clientCompany: "ABC Corporation",
    clientEmail: "john@abc.com",
    clientPhone: "+1-234-567-8900",
    clientType: "Corporate",
    roomNumber: "101",
    serviceDescription: "5-night stay - Deluxe Suite",
    items: [
      {
        id: "item-1",
        description: "Room Charges (5 nights @ $200/night)",
        quantity: 5,
        rate: 200,
        amount: 1000,
      },
      {
        id: "item-2",
        description: "Breakfast Service",
        quantity: 5,
        rate: 30,
        amount: 150,
      },
    ],
    issueDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    subtotal: 1150,
    taxRate: 0.1,
    taxAmount: 115,
    discountRate: 0,
    discountAmount: 0,
    totalAmount: 1265,
    status: "Paid",
    paymentMethod: "Card",
    transactionId: "TXN-001",
    notes: "Payment received successfully",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    paidDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "inv-002",
    invoiceNumber: "INV-2024-002",
    clientName: "Sarah Johnson",
    clientEmail: "sarah@email.com",
    clientPhone: "+1-234-567-8901",
    clientType: "Guest",
    roomNumber: "205",
    serviceDescription: "3-night stay - Standard Double",
    items: [
      {
        id: "item-1",
        description: "Room Charges (3 nights @ $150/night)",
        quantity: 3,
        rate: 150,
        amount: 450,
      },
      {
        id: "item-2",
        description: "Spa Service",
        quantity: 1,
        rate: 80,
        amount: 80,
      },
    ],
    issueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    subtotal: 530,
    taxRate: 0.1,
    taxAmount: 53,
    discountRate: 0.1,
    discountAmount: 58.3,
    totalAmount: 524.7,
    status: "Pending",
    notes: "Awaiting payment confirmation",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "inv-003",
    invoiceNumber: "INV-2024-003",
    clientName: "Michael Brown",
    clientCompany: "Tech Solutions Ltd",
    clientEmail: "michael@techsol.com",
    clientPhone: "+1-234-567-8902",
    clientType: "Corporate",
    roomNumber: "310",
    serviceDescription: "7-night corporate stay",
    items: [
      {
        id: "item-1",
        description: "Room Charges (7 nights @ $250/night)",
        quantity: 7,
        rate: 250,
        amount: 1750,
      },
      {
        id: "item-2",
        description: "Meeting Room Rental",
        quantity: 3,
        rate: 100,
        amount: 300,
      },
      {
        id: "item-3",
        description: "Catering Service",
        quantity: 1,
        rate: 500,
        amount: 500,
      },
    ],
    issueDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    subtotal: 2550,
    taxRate: 0.12,
    taxAmount: 306,
    discountRate: 0.05,
    discountAmount: 143,
    totalAmount: 2713,
    status: "Overdue",
    notes: "Payment overdue - reminder sent",
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "inv-004",
    invoiceNumber: "INV-2024-004",
    clientName: "Emma Wilson",
    clientEmail: "emma@email.com",
    clientPhone: "+1-234-567-8903",
    clientType: "Guest",
    roomNumber: "102",
    serviceDescription: "2-night stay - Single Room",
    items: [
      {
        id: "item-1",
        description: "Room Charges (2 nights @ $120/night)",
        quantity: 2,
        rate: 120,
        amount: 240,
      },
    ],
    issueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    subtotal: 240,
    taxRate: 0.1,
    taxAmount: 24,
    discountRate: 0,
    discountAmount: 0,
    totalAmount: 264,
    status: "Pending",
    notes: "New invoice",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "inv-005",
    invoiceNumber: "INV-2024-005",
    clientName: "Robert Taylor",
    clientCompany: "Global Enterprises",
    clientEmail: "robert@global.com",
    clientPhone: "+1-234-567-8904",
    clientType: "Corporate",
    roomNumber: "401-402",
    serviceDescription: "10-night executive suite booking",
    items: [
      {
        id: "item-1",
        description: "Executive Suite (10 nights @ $350/night)",
        quantity: 10,
        rate: 350,
        amount: 3500,
      },
      {
        id: "item-2",
        description: "Concierge Service",
        quantity: 10,
        rate: 50,
        amount: 500,
      },
    ],
    issueDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    subtotal: 4000,
    taxRate: 0.12,
    taxAmount: 480,
    discountRate: 0.05,
    discountAmount: 224,
    totalAmount: 4256,
    status: "Paid",
    paymentMethod: "Bank Transfer",
    transactionId: "TXN-005",
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    paidDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "inv-006",
    invoiceNumber: "INV-2024-006",
    clientName: "Patricia Martinez",
    clientEmail: "patricia@email.com",
    clientPhone: "+1-234-567-8905",
    clientType: "Guest",
    roomNumber: "203",
    serviceDescription: "4-night stay - Suite",
    items: [
      {
        id: "item-1",
        description: "Suite Room (4 nights @ $200/night)",
        quantity: 4,
        rate: 200,
        amount: 800,
      },
      {
        id: "item-2",
        description: "Restaurant Charges",
        quantity: 1,
        rate: 120,
        amount: 120,
      },
    ],
    issueDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    subtotal: 920,
    taxRate: 0.1,
    taxAmount: 92,
    discountRate: 0,
    discountAmount: 0,
    totalAmount: 1012,
    status: "Paid",
    paymentMethod: "Cash",
    transactionId: "CASH-001",
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    paidDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
